package main

import (
     "database/sql"
     _"github.com/mattn/go-sqlite3"
     "time"
 )

// DataStruct type is used for the json object generated by
// GetAllDataEndpoint, GetDataByIdEndpoint and DBQuery.
type DataStruct struct {
    ID        string       `json:"id,omitempty"`
    DeviceID  string       `json:"devid,omitempty"`
    Temp      float64      `json:"temp,omitempty"`
    Hum       float64      `json:"hum,omitempty"`
    Timestamp time.Time    `json:"timestamp,omitempty"`
}

// DBQuery function returns temperature, humidity and timestamp of creation
// of the specified sql query encoded in a json object structured by "DataStruct".
func DBQuery (query string) (data []DataStruct) {
  var dbid string
  var devid string
  var temp float64
  var hum float64
  var timestamp float64

  db, err := sql.Open("sqlite3", "./foo.db")
  checkErr(err)
  rows, err := db.Query(query)
  checkErr(err)
  for rows.Next() {
    err = rows.Scan(&dbid, &devid, &temp, &hum, &timestamp)
    checkErr(err)
    timestamp_human := time.Unix(int64(timestamp), 0)
    data = append(data, DataStruct{ID: dbid, DeviceID: devid, Temp: temp, Hum: hum, Timestamp: timestamp_human})
  }
    rows.Close()
    db.Close()
    return
}

// DataStructTemp type is used for the json object generated by
// GetTempDataByIdEndpoint and GetTempFromDb.
type DataStructTemp struct {
    Time             float64      `json:"time,omitempty"`
    Temperature      float64      `json:"temperature,omitempty"`
}

// GetTempFromDb function returns temperature and timestamp of creation
// of the specified sql query encoded in a json object structured by "DataStructTemp".
func GetTempFromDb (query string) (data []DataStructTemp) {
  var timestamp float64
  var temp float64

  db, err := sql.Open("sqlite3", "./foo.db")
  checkErr(err)
  rows, err := db.Query(query)
  checkErr(err)
  for rows.Next() {
    err = rows.Scan(&timestamp, &temp)
    checkErr(err)
    data = append(data, DataStructTemp{Time: timestamp, Temperature: temp})
  }
    rows.Close()
    db.Close()
    return
}

// DataStructHum type is used for the json object generated by
// GetHumDataByIdEndpoint and GetHumFromDb.
type DataStructHum struct {
    Time             float64      `json:"time,omitempty"`
    Humidity         float64      `json:"humidity,omitempty"`
}

// GetHumFromDb function returns humidity and timestamp of creation
// of the specified sql query encoded in a json object structured by "DataStructHum".
func GetHumFromDb (query string) (data []DataStructHum) {
  var timestamp float64
  var hum float64

  db, err := sql.Open("sqlite3", "./foo.db")
  checkErr(err)
  rows, err := db.Query(query)
  checkErr(err)
  for rows.Next() {
    err = rows.Scan(&timestamp, &hum)
    checkErr(err)
    data = append(data, DataStructHum{Time: timestamp, Humidity: hum})
  }
    rows.Close()
    db.Close()
    return
}
